[Enhancement] Implement Kalman Filter
ichiro-its/keisan pull request #72
Opened 2024-12-04 16:04 UTC by marfanr

## Jira Link: 

## Description

Describe problems, if any, clearly and concisely.
Describe any changes that have been made in this pull request.

## Type of Change

- [ ] Bugfix
- [ ] Enhancement
- [x] New feature
- [ ] Breaking change (fix or feature that would cause the existing functionality to not work as expected)

## How Has This Been Tested?

- [ ] New unit tests added.
- [ ] Manual tested.

## Checklist:

- [x] Using Branch Name Convention
    - `feature/JIRA-ID-SHORT-DESCRIPTION` if has a JIRA ticket
    - `enhancement/SHORT-DESCRIPTION` if has/has no JIRA ticket and contain enhancement
    - `hotfix/SHORT-DESCRIPTION` if the change doesn't need to be tested (urgent)
- [ ] I have commented on my code, particularly in hard-to-understand areas.
- [ ] I have made the documentation for the corresponding changes.

2024-12-05 04:00 UTC, threeal requested changes
Also fix the missing EoL.

2024-12-05 04:00 UTC, threeal commented on include/keisan/kalman.hpp
> +  Kalman(float dt, float std_dev_aceleration, Matrix<2, 1> std_measurement, Matrix<2, 1> acceleration);
Use `double` instead of `float` whenever possible.

2024-12-05 09:33 UTC, FaaizHaikal commented on include/keisan/kalman.hpp
> +#endif // KEISAN__KEISAN_HPP_
missing EOF line.

2024-12-05 09:33 UTC, FaaizHaikal commented on src/kalman.cpp
> +}
this too.

2024-12-05 15:59 UTC, threeal approved these changes

2024-12-05 16:55 UTC, FaaizHaikal approved these changes

2024-12-17 03:42 UTC, threeal requested changes

2024-12-17 03:42 UTC, threeal commented on include/keisan/matrix/matrix.hpp
> +  Matrix<M, N> round(const double & tolerance) const;
Pass `tolerance` as `double` directly instead:
```suggestion
  Matrix<M, N> round(double tolerance) const;
```

2025-01-13 06:37 UTC, threeal approved these changes

2025-01-18 06:12 UTC, merged